"""Center-owned meta tool names."""

CENTER_META_TOOLS = {
    "node.list",
    "node.status",
    "capability.search",
    "capability.describe",
    "context.inspect",
    "context.expand",
    "context.tail",
    "context.schema",
    "context.search",
    "context.status",
    "artifact.list",
    "artifact.get",
    "artifact.present",
    "artifact.deploy.preflight",
    "artifact.deploy",
    "operation.status",
    "operation.cancel",
    "transfer.preflight",
    "transfer.create",
    "transfer.resume",
    "transfer.status",
    "transfer.cancel",
}
