"""add_maintenance_plan_tables

Revision ID: 4718287cbf6f
Revises: 62f99909f120
Create Date: 2026-06-20 23:07:59.278164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4718287cbf6f'
down_revision: Union[str, Sequence[str], None] = '62f99909f120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_artifacts_artifact_id'), 'maintenance_artifacts', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_maintenance_artifacts_run_id'), 'maintenance_artifacts', ['run_id'], unique=False)
    op.create_table('maintenance_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('target_node_id', sa.String(length=128), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('resource_keys', sqlite.JSON(), nullable=True),
    sa.Column('max_total_duration_sec', sa.Integer(), nullable=True),
    sa.Column('rollback_strategy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plans_plan_id'), 'maintenance_plans', ['plan_id'], unique=True)
    op.create_table('maintenance_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_runs_plan_id'), 'maintenance_runs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_maintenance_runs_run_id'), 'maintenance_runs', ['run_id'], unique=True)
    op.create_table('maintenance_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('order_', sa.Integer(), nullable=False),
    sa.Column('function_name', sa.String(length=256), nullable=False),
    sa.Column('input_', sqlite.JSON(), nullable=True),
    sa.Column('depends_on', sqlite.JSON(), nullable=True),
    sa.Column('continue_on_failure', sa.Boolean(), nullable=False),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.Column('resource_keys', sqlite.JSON(), nullable=True),
    sa.Column('expected_result_schema', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('invocation_id', sa.String(length=32), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_steps_plan_id'), 'maintenance_steps', ['plan_id'], unique=False)
    op.create_index(op.f('ix_maintenance_steps_step_id'), 'maintenance_steps', ['step_id'], unique=True)
    op.create_table('rollback_hints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('hint_id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('function_name', sa.String(length=256), nullable=True),
    sa.Column('input_', sqlite.JSON(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollback_hints_hint_id'), 'rollback_hints', ['hint_id'], unique=True)
    op.create_index(op.f('ix_rollback_hints_run_id'), 'rollback_hints', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rollback_hints_run_id'), table_name='rollback_hints')
    op.drop_index(op.f('ix_rollback_hints_hint_id'), table_name='rollback_hints')
    op.drop_table('rollback_hints')
    op.drop_index(op.f('ix_maintenance_steps_step_id'), table_name='maintenance_steps')
    op.drop_index(op.f('ix_maintenance_steps_plan_id'), table_name='maintenance_steps')
    op.drop_table('maintenance_steps')
    op.drop_index(op.f('ix_maintenance_runs_run_id'), table_name='maintenance_runs')
    op.drop_index(op.f('ix_maintenance_runs_plan_id'), table_name='maintenance_runs')
    op.drop_table('maintenance_runs')
    op.drop_index(op.f('ix_maintenance_plans_plan_id'), table_name='maintenance_plans')
    op.drop_table('maintenance_plans')
    op.drop_index(op.f('ix_maintenance_artifacts_run_id'), table_name='maintenance_artifacts')
    op.drop_index(op.f('ix_maintenance_artifacts_artifact_id'), table_name='maintenance_artifacts')
    op.drop_table('maintenance_artifacts')
    # ### end Alembic commands ###
