"""add_consumed_invocation_id_to_approval

Revision ID: 62f99909f120
Revises: 557e73d411cf
Create Date: 2026-06-20 18:54:33.722573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f99909f120'
down_revision: Union[str, Sequence[str], None] = '557e73d411cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('consumed_invocation_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'consumed_invocation_id')
    # ### end Alembic commands ###
