"""change_api_tokens_unique_to_hash_scope_pair

Revision ID: 714e63ed74e2
Revises: 4718287cbf6f
Create Date: 2026-06-20 23:52:36.253398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714e63ed74e2'
down_revision: Union[str, Sequence[str], None] = '4718287cbf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint('uq_api_tokens_hash_scope', 'api_tokens', ['token_hash', 'scope'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_api_tokens_hash_scope', 'api_tokens', type_='unique')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###
