"""add_approval_and_resource_lock_tables

Revision ID: 7c708b5743e4
Revises: b49d049ffc89
Create Date: 2026-06-20 13:04:15.549669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7c708b5743e4'
down_revision: Union[str, Sequence[str], None] = 'b49d049ffc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('invocation_id', sa.String(length=32), nullable=True),
    sa.Column('function_name', sa.String(length=256), nullable=False),
    sa.Column('target_node_id', sa.String(length=128), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=False),
    sa.Column('input_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.Column('resource_keys', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('denied_by', sa.String(length=128), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_actor_id'), 'approval_requests', ['actor_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_approval_id'), 'approval_requests', ['approval_id'], unique=True)
    op.create_index(op.f('ix_approval_requests_session_id'), 'approval_requests', ['session_id'], unique=False)
    op.create_table('resource_locks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lock_id', sa.String(length=32), nullable=False),
    sa.Column('resource_key', sa.String(length=512), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('invocation_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_locks_job_id'), 'resource_locks', ['job_id'], unique=False)
    op.create_index(op.f('ix_resource_locks_lock_id'), 'resource_locks', ['lock_id'], unique=True)
    op.create_index(op.f('ix_resource_locks_resource_key'), 'resource_locks', ['resource_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_locks_resource_key'), table_name='resource_locks')
    op.drop_index(op.f('ix_resource_locks_lock_id'), table_name='resource_locks')
    op.drop_index(op.f('ix_resource_locks_job_id'), table_name='resource_locks')
    op.drop_table('resource_locks')
    op.drop_index(op.f('ix_approval_requests_session_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approval_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_actor_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
