"""initial_schema

Revision ID: 93c58bcdf57c
Revises: 
Create Date: 2026-06-19 21:24:02.981478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '93c58bcdf57c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invocations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('invocation_id', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('function_name', sa.String(length=256), nullable=False),
    sa.Column('input_payload', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('target_node_id', sa.String(length=128), nullable=True),
    sa.Column('call_path', sqlite.JSON(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=True),
    sa.Column('max_total_duration_sec', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invocations_actor_id'), 'invocations', ['actor_id'], unique=False)
    op.create_index(op.f('ix_invocations_invocation_id'), 'invocations', ['invocation_id'], unique=True)
    op.create_index(op.f('ix_invocations_session_id'), 'invocations', ['session_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('invocation_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('function_name', sa.String(length=256), nullable=False),
    sa.Column('input_payload', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.Column('lease_sec', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sqlite.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=256), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('progress_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_invocation_id'), 'jobs', ['invocation_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_node_id'), 'jobs', ['node_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('node_name', sa.String(length=256), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('locality', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('daemon_version', sa.String(length=32), nullable=True),
    sa.Column('platform_os', sa.String(length=32), nullable=True),
    sa.Column('platform_arch', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_interval_sec', sa.Integer(), nullable=True),
    sa.Column('job_delivery_mode', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_node_id'), 'nodes', ['node_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=256), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_actor_id'), 'sessions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('global_seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('invocation_id', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('node_id', sa.String(length=128), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_actor_id'), 'timeline_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_global_seq'), 'timeline_events', ['global_seq'], unique=False)
    op.create_index(op.f('ix_timeline_events_invocation_id'), 'timeline_events', ['invocation_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_job_id'), 'timeline_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_message_id'), 'timeline_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_node_id'), 'timeline_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_session_id'), 'timeline_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_timestamp'), 'timeline_events', ['timestamp'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('node_record_id', sa.String(length=32), nullable=False),
    sa.Column('plugin_id', sa.String(length=256), nullable=False),
    sa.Column('plugin_version', sa.String(length=32), nullable=False),
    sa.Column('capability_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_schema', sqlite.JSON(), nullable=True),
    sa.Column('output_schema', sqlite.JSON(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=True),
    sa.Column('effect', sa.String(length=16), nullable=True),
    sa.Column('timeout_sec', sa.Integer(), nullable=True),
    sa.Column('idempotency', sa.String(length=32), nullable=True),
    sa.Column('resource_keys', sqlite.JSON(), nullable=True),
    sa.Column('conflict_policy', sa.String(length=32), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=True),
    sa.Column('ttl_sec', sa.Integer(), nullable=True),
    sa.Column('value_schema', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_record_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_name'), 'capabilities', ['name'], unique=False)
    op.create_index(op.f('ix_capabilities_node_record_id'), 'capabilities', ['node_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capabilities_node_record_id'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_name'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_timeline_events_timestamp'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_session_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_node_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_message_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_job_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_invocation_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_global_seq'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_actor_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_actor_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_nodes_node_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_jobs_node_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_invocation_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_invocations_session_id'), table_name='invocations')
    op.drop_index(op.f('ix_invocations_invocation_id'), table_name='invocations')
    op.drop_index(op.f('ix_invocations_actor_id'), table_name='invocations')
    op.drop_table('invocations')
    # ### end Alembic commands ###
