"""add_api_tokens_table

Revision ID: 9961139e666c
Revises: 93c58bcdf57c
Create Date: 2026-06-20 00:09:58.253655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9961139e666c'
down_revision: Union[str, Sequence[str], None] = '93c58bcdf57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
