"""l2c_maintenance_artifact_rollback

Revision ID: ba40e5beb506
Revises: a7b5f8f32d89
Create Date: 2026-06-21 03:12:19.036105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ba40e5beb506'
down_revision: Union[str, Sequence[str], None] = 'a7b5f8f32d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_artifacts', sa.Column('invocation_id', sa.String(length=32), nullable=True))
    op.add_column('maintenance_artifacts', sa.Column('job_id', sa.String(length=32), nullable=True))
    op.add_column('maintenance_artifacts', sa.Column('kind', sa.String(length=32), nullable=False))
    op.add_column('maintenance_artifacts', sa.Column('data', sqlite.JSON(), nullable=True))
    op.add_column('maintenance_artifacts', sa.Column('summary', sqlite.JSON(), nullable=True))
    op.alter_column('maintenance_artifacts', 'content_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_maintenance_artifacts_created_at'), 'maintenance_artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenance_artifacts_step_id'), 'maintenance_artifacts', ['step_id'], unique=False)
    op.drop_column('maintenance_artifacts', 'artifact_type')
    op.drop_column('maintenance_artifacts', 'sha256')
    op.drop_column('maintenance_artifacts', 'storage_ref')
    op.drop_column('maintenance_artifacts', 'size_bytes')
    op.add_column('maintenance_runs', sa.Column('rollback_recommended', sa.Boolean(), nullable=False))
    op.add_column('maintenance_steps', sa.Column('rollback_hint', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_steps', 'rollback_hint')
    op.drop_column('maintenance_runs', 'rollback_recommended')
    op.add_column('maintenance_artifacts', sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('maintenance_artifacts', sa.Column('storage_ref', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('maintenance_artifacts', sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('maintenance_artifacts', sa.Column('artifact_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_maintenance_artifacts_step_id'), table_name='maintenance_artifacts')
    op.drop_index(op.f('ix_maintenance_artifacts_created_at'), table_name='maintenance_artifacts')
    op.alter_column('maintenance_artifacts', 'content_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('maintenance_artifacts', 'summary')
    op.drop_column('maintenance_artifacts', 'data')
    op.drop_column('maintenance_artifacts', 'kind')
    op.drop_column('maintenance_artifacts', 'job_id')
    op.drop_column('maintenance_artifacts', 'invocation_id')
    # ### end Alembic commands ###
